xpay: fakenet test: move funds when payment succeeds
Improved the fakenet simulation by moving funds after a payment
succeeds.

This triggers a bug in xpay. At PAYING Node #8 xpay fails after trying
many 1msat routes:
```
error: {'code': 209, 'message': "Timed out after after 842 attempts.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102199msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102197msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102196msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102195msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102194msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102193msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102192msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102191msat.
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198102190msat
...
We got temporary_channel_failure for 45210x2134x44171/0, assuming it can't carry 198101779msat.
Payment of 9996982msat reached destination, but timed out before the rest arrived..
Payment of 998000msat reached destination, but timed out before the rest arrived..
Payment of 3000000msat reached destination, but timed out before the rest arrived..
Payment of 197000000msat reached destination, but timed out before the rest arrived..
Payment of 91005018msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived..
...
Payment of 1msat reached destination, but timed out before the rest arrived..
Payment of 1msat reached destination, but timed out before the rest arrived.. "}
```

A lower bound learned for channel 45210x2134x44171 at a previous payment
is to blame. xpay thinks it has enough liquidity for ~198ksat 100% sure
and it keeps trying and failing, while refine produces 1msat alternative
payment routes after every MCF computation because fees don't fit even
for our current knowledge. As a matter of fact the computed routes are
attributed a very low probability of success at around ~0.4%. This is a
case for which our assumption that "the cost of X+fees is not much
greater than the cost of X" breaks down.

To fix this:
-  we need xpay to relax that lower bound. The multiple failures are
empirical evidence that our knowledge is wrong and we should correct it,
- the probability cost function should add a buffer for hypothetical
  fees, ie. New_cost(x) = Old_cost(x + fees).

Changelog-None

Signed-off-by: Lagrang3 <lagrang3@protonmail.com>