flake: fix missing dependencies for make
Running `nix develop`, `./configure` and then `make` fails with this error:

```
tests/fuzz/fuzz-hmac-sha256.c:8:10: fatal error: openssl/evp.h: No such file or directory
```

After adding `openssl`, without `protobuf`, `make` fails while building
`cln-grpc v0.5.0` because the `protoc` binary is missing.