tests: lower testpluguv's required python version
uv would use python 3.14 which currently leads to an error because of a build dependency update

```
× Failed to build `coincurve==20.0.0`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `hatchling.build.build_wheel` failed (exit status: 7)

      [stderr]
      ERROR: Use build.verbose instead of cmake.verbose for scikit-build-core >= 0.10

      hint: This usually indicates a problem with the package or the build environment.
  help: `coincurve` (v20.0.0) was included because `cln-meta-project` (v0.1.0) depends on `pyln-proto` (v26.6.2) which depends on `coincurve`
```

Changelog-None