pytest: fix use of deprecated `getroute` in tests/test_misc.py::test_graceful_htlc
Merge conflict:

```
FAILED tests/test_misc.py::test_graceful_htlc - pyln.client.lightning.RpcError: RPC call failed: method: getroute, payload: {'id': '03cecbfdc68544cc596223b68ce0710c9e5d2c9cb317ee07822d95079acc703d31', 'amount_msat': 10000, 'riskfactor': 1, 'cltv': 9}, error: {'code': -32601, 'message': 'Command "getroute" is deprecated'}
```

Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>