common/wireaddr: fix GCC 15 const-qualifier errors
GCC 15 propagates the const qualifier through strchr/strrchr, so the
result of strchr(const char *, c) is const char *. Declaring the locals
as char * triggers -Werror=discarded-qualifiers:

    common/wireaddr.c: In function 'separate_address_and_port':
    common/wireaddr.c:297:29: error: initialization discards 'const'
      qualifier from pointer target type [-Werror=discarded-qualifiers]
    common/wireaddr.c:304:27: error: assignment discards 'const'
      qualifier from pointer target type [-Werror=discarded-qualifiers]

Make portcolon and end const char * to match; both are only read.

Fixes: https://github.com/ElementsProject/lightning/issues/9074
Changelog-Fixed: build: fix build errors with GCC 15 (Arch Linux).