listtransactions: remove annotations
This is a minimal subset of the master commit b8aa3a579ea03b5eecde44d163fdb12deddf2c8b
which fixes compile with --enable-experimental-features:

```
wallet/walletrpc.c: In function 'json_transaction_details':
wallet/walletrpc.c:521:56: error: 'const struct wallet_transaction' has no member named 'input_annotations'
  521 |                         struct tx_annotation *ann = &tx->input_annotations[i];
      |                                                        ^~
wallet/walletrpc.c:551:56: error: 'const struct wallet_transaction' has no member named 'output_annotations'
  551 |                         struct tx_annotation *ann = &tx->output_annotations[i];
      |                                                        ^~
```

Reported-by: @whitslack
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
Changelog-Fixed: build: compilation error when `--enable-experimental-features` configured.