pytest: make test_connect use an unknown id.
This test failed:

       AssertionError: "No address known" does not match "RPC call failed: {'code': -1, 'message': 'Connection establishment: Connection timed out'}, method: connect, payload: {'id': '032cf15d1ad9c4a08d26eab1918f732d8ef8fdc6abb9640bf3db174372c491304e'}"

Because someone seems to have actually used this ID on testnet!

	DEBUG:root:lightningd-1: 2018-06-19T07:14:39.413Z lightning_gossipd(3467): Resolved ln1qvk0zhg6m8z2prfxa2cerrmn9k803lwx4wukgzlnmvt5xukyjycyugwvuk8.lseed.bitcoinstats.com to 91.194.91.220:9735

Change the last digit, creating an unknowable ID so this can't happen again.

Reported-by: @sturles
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>