Do not use FEERATE_MAX in 0 starting loop.
This will cause to loop 1 time more than necessary.
It was causing the following error in clang build
in macos.

```
lightningd/chaintopology.c:351:29: error: result of comparison of constant 8 with expression of type 'enum feerate' is always true
      [-Werror,-Wtautological-constant-out-of-range-compare]
        for (enum feerate f = 0; f < NUM_FEERATES; f++) {
```