ccan: fix compilation error about const types
This commit fixes the following build error

ccan/ccan/fdpass/fdpass.c:16:8: error: variable length array folded to
constant array as an extension [-Werror,-Wgnu-folding-constant] char
buf[CMSG_SPACE(sizeof(fd))];

This is strange from a UNIX proxpective because the macros
return a size_t and the size_t is a unsigned integer type that
should be compatible with the array declaration.

But for some plaform/or compiler this looks like not true?

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>