pytest: explicitly test failed case exposed by race.
This showed up as a flake, where we "got lucky" and the sendpay resolved before waitsendpay was called.  Instead, make this race explicit, so we can test it.

```
        # FIXME: #define PAY_UNPARSEABLE_ONION		202
        PAY_UNPARSEABLE_ONION = 202
>       assert err.value.error['code'] == PAY_UNPARSEABLE_ONION
E       assert 204 == 202

tests/test_misc.py:2152: AssertionError
```

Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>