Use __COUNTER__ in addition to __LINE__ in autodata
The use of __LINE__ runs the chance of collision, which occured in https://github.com/ElementsProject/lightning/pull/4756/checks?check_run_id=3529432371

Adding __COUNTER__ reduces the chance of collision issue but requires AUTODATA(..) to be slighting restructured.

Collision details from build:

In file included from ./common/type_to_string.h:5,
                 from ./lightningd/log.h:9,
                 from wallet/test/run-wallet.c:1:
ccan/ccan/autodata/autodata.h:83:36: error: redefinition of ‘autodata_json_command_2577’
   83 | #define AUTODATA_VAR__(name, line) autodata_##name##_##line
      |                                    ^~~~~~~~~
ccan/ccan/autodata/autodata.h:84:35: note: in expansion of macro ‘AUTODATA_VAR__’
   84 | #define AUTODATA_VAR_(name, line) AUTODATA_VAR__(name, line)
      |                                   ^~~~~~~~~~~~~~
ccan/ccan/autodata/autodata.h:46:2: note: in expansion of macro ‘AUTODATA_VAR_’
   46 |  AUTODATA_VAR_(name, __LINE__) = (ptr);
      |  ^~~~~~~~~~~~~
./lightningd/peer_htlcs.c:2577:1: note: in expansion of macro ‘AUTODATA’
 2577 | AUTODATA(json_command, &dev_ignore_htlcs);
      | ^~~~~~~~
ccan/ccan/autodata/autodata.h:83:36: note: previous definition of ‘autodata_json_command_2577’ was here
   83 | #define AUTODATA_VAR__(name, line) autodata_##name##_##line
      |                                    ^~~~~~~~~
ccan/ccan/autodata/autodata.h:84:35: note: in expansion of macro ‘AUTODATA_VAR__’
   84 | #define AUTODATA_VAR_(name, line) AUTODATA_VAR__(name, line)
      |                                   ^~~~~~~~~~~~~~
ccan/ccan/autodata/autodata.h:46:2: note: in expansion of macro ‘AUTODATA_VAR_’
   46 |  AUTODATA_VAR_(name, __LINE__) = (ptr);
      |  ^~~~~~~~~~~~~
./lightningd/peer_control.c:2577:1: note: in expansion of macro ‘AUTODATA’
 2577 | AUTODATA(json_command, &dev_fail_command);
      | ^~~~~~~~